# Generated by Django 4.0.5 on 2022-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_filme_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
