# Generated by Django 4.0.5 on 2022-06-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_filme_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='descrição',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='título',
        ),
        migrations.AddField(
            model_name='filme',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='filme',
            name='titulo',
            field=models.TextField(blank=True, verbose_name='título'),
        ),
    ]
