# Generated by Django 4.0.5 on 2022-06-19 02:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=2048)),
                ('descricao', models.TextField(default='')),
                ('nota', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.console')),
            ],
        ),
    ]
