# Generated by Django 4.0.5 on 2022-06-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_console_gamu'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamu',
            name='capa',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
