# Generated by Django 4.0.5 on 2022-06-24 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2048, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='ave',
            options={'ordering': ['nome_cientifico']},
        ),
        migrations.AddField(
            model_name='ave',
            name='abundancia_relativa',
            field=models.IntegerField(null=True, verbose_name='frequência de ocorrência'),
        ),
        migrations.AddField(
            model_name='ave',
            name='autor',
            field=models.CharField(max_length=2048, null=True, verbose_name='nome do autor'),
        ),
        migrations.AddField(
            model_name='ave',
            name='frequencia_ocorrencia',
            field=models.IntegerField(null=True, verbose_name='frequência de ocorrência'),
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2048, unique=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.ordem')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='ave',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aves.familia', verbose_name='família'),
        ),
    ]
