# Generated by Django 4.0.5 on 2022-06-24 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0003_remove_ave_descricao_ave_estado_iucn_int_ave_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familia',
            options={'ordering': ['nome'], 'verbose_name': 'família'},
        ),
        migrations.AlterModelOptions(
            name='ordem',
            options={'ordering': ['nome'], 'verbose_name_plural': 'ordens'},
        ),
        migrations.CreateModel(
            name='InfoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=2048, verbose_name='título')),
                ('texto', models.TextField()),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.ave')),
            ],
            options={
                'verbose_name': 'informação extra',
                'verbose_name_plural': 'informações extras',
            },
        ),
    ]
