# Generated by Django 4.0.5 on 2022-06-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0005_alter_ave_abundancia_relativa_alter_ave_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('leganda', models.CharField(blank=True, max_length=2048)),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.ave')),
            ],
            options={
                'verbose_name': 'foto de ave',
                'verbose_name_plural': 'fotos de aves',
            },
        ),
    ]
