# Generated by Django 4.0.5 on 2022-06-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamu', '0002_screenshot_descricaoextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='legenda',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
