# Generated by Django 4.0.5 on 2022-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0007_classifiextra_ordem_classifiextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='autor',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='ave',
            name='abundancia_relativa',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='abundância relativa'),
        ),
    ]
