# Generated by Django 4.0.5 on 2022-06-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0008_familia_autor_alter_ave_abundancia_relativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aves.ordem'),
        ),
    ]
