# Generated by Django 4.0.5 on 2022-06-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0009_alter_familia_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='ordem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aves.ordem'),
            preserve_default=False,
        ),
    ]
